stages:
    - build

create_badge_svg:
  stage: build
  image: python:3.6.6
  tags:
    - docker
  before_script:
    - echo "Python other dependencies installation"
    - mkdir badges
    - pip install anybadge
  script:
    - echo "Please add your anybadge definition into script part"
    - echo "Documentation: https://github.com/jongracecox/anybadge#basic-usage"
  artifacts:
    paths:
        - badges/
    when: always
    expire_in: 4 weeks